server:
  port: 10020

spring:
  application:
    name: eureka-client-provider

eureka:
  client:
    # 是否将自己注册到Eureka Server,默认为true
    register-with-eureka: true
    # 是否从eureka server获取注册信息
    fetch-registry: true
    # 设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://quaintlocal-1.com:10010/eureka/,http://quaintlocal-2.com:10011/eureka/
    # 是否开启健康检查
    healthcheck:
      enabled: true
  instance:
    hostname: localhost

management:
  endpoint:
    shutdown:
      # 是否可以 停止该 服务
      enabled: true
  endpoints:
    web:
      exposure:
        # 查看所有状态
        include: '*'

