server:
  port: 10022

spring:
  application:
    name: eureka-client-consumer

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true
    register-with-eureka: true
    #是否从eureka server获取注册信息
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://quaintlocal-1.com:10010/eureka/,http://quaintlocal-2.com:10011/eureka/
  instance:
    hostname: localhost

# 配置负载均衡策略
#eureka-client-consumer:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule