server:
  port: 9999

spring:
  application:
    name: provider-server

eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true
    register-with-eureka: true
    #是否从eureka server获取注册信息
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://quaintlocal-1.com:10010/eureka/
  instance:
    hostname: localhost